# Existing imports
from .modelscope_image_node import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_MAPPINGS
from .modelscope_vision_node import NODE_CLASS_MAPPINGS as VISION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISION_DISPLAY_MAPPINGS
from .modelscope_text_node import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_MAPPINGS

# New: Import image caption node mappings
from .modelscope_image_caption_node import NODE_CLASS_MAPPINGS as IMAGE_CAPTION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_CAPTION_DISPLAY_MAPPINGS

# Merge all node mappings
NODE_CLASS_MAPPINGS = {
    **IMAGE_MAPPINGS, **VISION_MAPPINGS,
    **TEXT_MAPPINGS, **IMAGE_CAPTION_MAPPINGS
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_DISPLAY_MAPPINGS, **VISION_DISPLAY_MAPPINGS,
    **TEXT_DISPLAY_MAPPINGS, **IMAGE_CAPTION_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

WEB_DIRECTORY = "./js"
__version__ = "1.0.0"
